//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RatingAPI.AuthenticationModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogTable
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> timestamp { get; set; }
        public string message { get; set; }
    }
}
