//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RatingAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuantityRate
    {
        public int ID { get; set; }
        public Nullable<int> TariffGroupID { get; set; }
        public Nullable<int> QuantityFrom { get; set; }
        public Nullable<int> QuantityTo { get; set; }
        public string ZoneName { get; set; }
        public Nullable<decimal> Rate { get; set; }
    }
}
