//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RatingAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecialRate
    {
        public int ID { get; set; }
        public Nullable<int> ClientID { get; set; }
        public string Service { get; set; }
        public string Zone { get; set; }
        public Nullable<decimal> FromWeight { get; set; }
        public Nullable<decimal> ToWeight { get; set; }
        public Nullable<decimal> Rate { get; set; }
    }
}
