//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RatingAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebRespons
    {
        public int ID { get; set; }
        public Nullable<int> WebRequestID { get; set; }
        public Nullable<int> StatusCode { get; set; }
        public Nullable<int> Zone { get; set; }
        public string Service { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> Weight { get; set; }
        public Nullable<int> Milliseconds { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public string ErrorMessages { get; set; }
        public Nullable<decimal> CubeWeight { get; set; }
        public Nullable<int> Pieces { get; set; }
        public Nullable<decimal> FuelRate { get; set; }
        public Nullable<decimal> AccessorialsRate { get; set; }
        public Nullable<decimal> SizeSurchargeRate { get; set; }
        public Nullable<decimal> GirthRate { get; set; }
        public WebRequestDimension[] Dimensions { get; set; }
    }
}
