//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RatingAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebRequest
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public Nullable<int> APIUserID { get; set; }
        public string Service { get; set; }
        public string AuthenticationToken { get; set; }
        public string FromPostal { get; set; }
        public string ToPostal { get; set; }
        public Nullable<int> Pieces { get; set; }
        public WebRequestAccessorial[] Accessorials { get; set; }
        public WebRequestDimension[] Dimensions { get; set; }
    }
}
